# 04 Train WLASL300 BiGRU + Temporal Attention Model

## Purpose

This notebook trains the selected WLASL100 architecture on WLASL300.

## Why this model

From WLASL100 experiments, **BiGRU + Temporal Attention** outperformed the baseline BiLSTM and the Small Transformer Encoder. Therefore, this notebook scales the winning architecture to 300 ASL signs.

## Model strategy

The model uses:

- MediaPipe keypoints
- Velocity/motion features
- Global train-set normalisation
- Balanced class sampling
- BiGRU sequence modelling
- Temporal attention pooling
- AdamW optimiser
- Learning-rate scheduling
- Gradient clipping
- Early stopping
- Top-1, Top-3, Top-5 accuracy
- Macro F1-score

In [2]:
from pathlib import Path
import random
import time
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

from tqdm.auto import tqdm
from sklearn.metrics import accuracy_score, f1_score

warnings.filterwarnings("ignore", category=UserWarning)

## 1. Set paths and training settings

In [3]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

PROJECT_ROOT = Path("E:/Be_My_Ear")

DATASET_NAME = "WLASL300"
PREFIX = "wlasl300"

BASE_DIR = PROJECT_ROOT / "data" / "processed" / "ASL" / DATASET_NAME
CLEAN_INDEX_FILE = BASE_DIR / f"{PREFIX}_clean_keypoint_index.csv"

MODEL_DIR = PROJECT_ROOT / "models" / "ASL" / DATASET_NAME
MODEL_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = MODEL_DIR / f"bigru_attention_{PREFIX}.pt"
HISTORY_PATH = MODEL_DIR / f"bigru_attention_{PREFIX}_history.csv"
NORM_STATS_PATH = MODEL_DIR / f"{PREFIX}_train_norm_stats.npz"

BATCH_SIZE = 32
USE_VELOCITY = True
INPUT_SIZE = 516
SEQUENCE_LENGTH = 60
EPOCHS = 60
EARLY_STOPPING_PATIENCE = 15

print("Dataset:", DATASET_NAME)
print("Clean index exists:", CLEAN_INDEX_FILE.exists())
print("Model will save to:", MODEL_PATH)

Dataset: WLASL300
Clean index exists: True
Model will save to: E:\Be_My_Ear\models\ASL\WLASL300\bigru_attention_wlasl300.pt

## 2. Load clean WLASL300 dataset

In [4]:
df = pd.read_csv(CLEAN_INDEX_FILE)

print("Clean samples:", len(df))
print("Classes:", df["label_id"].nunique())
print("Example keypoint path:", df.iloc[0]["keypoint_path"])

df.head()

Clean samples: 2660
Classes: 300
Example keypoint path: E:\Be_My_Ear\data\processed\ASL\WLASL300\keypoints\65096.npy

,video_id,gloss,label_id,original_class_id,video_path,keypoint_path,zero_ratio
0,65096,arrive,10,182,E:\Be_My_Ear\data\raw\ASL\videos\65096.mp4,E:\Be_My_Ear\data\processed\ASL\WLASL300\keypo...,0.236047
1,65639,environment,107,279,E:\Be_My_Ear\data\raw\ASL\videos\65639.mp4,E:\Be_My_Ear\data\processed\ASL\WLASL300\keypo...,0.227907
2,10112,chat,53,191,E:\Be_My_Ear\data\raw\ASL\videos\10112.mp4,E:\Be_My_Ear\data\processed\ASL\WLASL300\keypo...,0.028876
3,55348,student,253,247,E:\Be_My_Ear\data\raw\ASL\videos\55348.mp4,E:\Be_My_Ear\data\processed\ASL\WLASL300\keypo...,0.297093
4,65092,argue,9,258,E:\Be_My_Ear\data\raw\ASL\videos\65092.mp4,E:\Be_My_Ear\data\processed\ASL\WLASL300\keypo...,0.244186

## 3. Create train / validation / test split

In [5]:
train_records = []
val_records = []
test_records = []

for label_id, group in df.groupby("label_id"):
    group = group.sample(frac=1, random_state=SEED).reset_index(drop=True)

    n = len(group)
    n_test = max(1, int(round(n * 0.15)))
    n_val = max(1, int(round(n * 0.15)))

    test_records.append(group.iloc[:n_test])
    val_records.append(group.iloc[n_test:n_test + n_val])
    train_records.append(group.iloc[n_test + n_val:])

train_df = pd.concat(train_records).sample(frac=1, random_state=SEED).reset_index(drop=True)
val_df = pd.concat(val_records).sample(frac=1, random_state=SEED).reset_index(drop=True)
test_df = pd.concat(test_records).sample(frac=1, random_state=SEED).reset_index(drop=True)

print("Train samples:", len(train_df))
print("Validation samples:", len(val_df))
print("Test samples:", len(test_df))
print("Train classes:", train_df["label_id"].nunique())
print("Validation classes:", val_df["label_id"].nunique())
print("Test classes:", test_df["label_id"].nunique())

Train samples: 1870
Validation samples: 395
Test samples: 395
Train classes: 300
Validation classes: 300
Test classes: 300

## 4. Compute global train-set normalisation

In [6]:
def compute_train_normalisation_stats(train_dataframe):
    total_sum = None
    total_sq_sum = None
    total_count = 0

    for path in tqdm(train_dataframe["keypoint_path"], desc="Computing train mean/std"):
        arr = np.load(path).astype(np.float32)

        if total_sum is None:
            total_sum = arr.sum(axis=0)
            total_sq_sum = (arr ** 2).sum(axis=0)
        else:
            total_sum += arr.sum(axis=0)
            total_sq_sum += (arr ** 2).sum(axis=0)

        total_count += arr.shape[0]

    mean = total_sum / total_count
    variance = (total_sq_sum / total_count) - (mean ** 2)
    variance = np.maximum(variance, 1e-6)
    std = np.sqrt(variance)

    return mean.astype(np.float32), std.astype(np.float32)

train_mean, train_std = compute_train_normalisation_stats(train_df)
np.savez(NORM_STATS_PATH, mean=train_mean, std=train_std)

print("Saved normalisation stats to:", NORM_STATS_PATH)
print("Mean shape:", train_mean.shape)
print("Std shape:", train_std.shape)

Computing train mean/std: 100%|██████████| 1870/1870 [00:02<00:00, 836.64it/s]

Saved normalisation stats to: E:\Be_My_Ear\models\ASL\WLASL300\wlasl300_train_norm_stats.npz
Mean shape: (258,)
Std shape: (258,)

## 5. Create PyTorch dataset and balanced data loaders

In [7]:
class SignKeypointDataset(Dataset):
    def __init__(self, dataframe, mean, std, use_velocity=True):
        self.dataframe = dataframe.reset_index(drop=True)
        self.mean = mean.reshape(1, -1).astype(np.float32)
        self.std = std.reshape(1, -1).astype(np.float32)
        self.use_velocity = use_velocity

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        row = self.dataframe.iloc[idx]

        keypoints = np.load(row["keypoint_path"]).astype(np.float32)
        keypoints = (keypoints - self.mean) / (self.std + 1e-6)

        if self.use_velocity:
            velocity = np.zeros_like(keypoints, dtype=np.float32)
            velocity[1:] = keypoints[1:] - keypoints[:-1]
            features = np.concatenate([keypoints, velocity], axis=1)
        else:
            features = keypoints

        label = int(row["label_id"])

        return torch.tensor(features, dtype=torch.float32), torch.tensor(label, dtype=torch.long)

train_dataset = SignKeypointDataset(train_df, train_mean, train_std, USE_VELOCITY)
val_dataset = SignKeypointDataset(val_df, train_mean, train_std, USE_VELOCITY)
test_dataset = SignKeypointDataset(test_df, train_mean, train_std, USE_VELOCITY)

class_counts = train_df["label_id"].value_counts().to_dict()
sample_weights = train_df["label_id"].map(lambda label: 1.0 / class_counts[label]).values
sampler = WeightedRandomSampler(torch.DoubleTensor(sample_weights), num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=sampler, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

x_batch, y_batch = next(iter(train_loader))

print("Input batch shape:", x_batch.shape)
print("Label batch shape:", y_batch.shape)

Input batch shape: torch.Size([32, 60, 516])
Label batch shape: torch.Size([32])

## 6. Define BiGRU + Temporal Attention model

In [8]:
class BiGRUAttentionModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes, num_layers=2, dropout=0.4):
        super().__init__()

        self.input_projection = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

        self.gru = nn.GRU(
            input_size=hidden_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout if num_layers > 1 else 0
        )

        self.attention = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, num_classes)
        )

    def forward(self, x):
        x = self.input_projection(x)
        gru_out, _ = self.gru(x)

        attention_scores = self.attention(gru_out).squeeze(-1)
        attention_weights = torch.softmax(attention_scores, dim=1).unsqueeze(-1)

        context = torch.sum(gru_out * attention_weights, dim=1)
        logits = self.classifier(context)

        return logits

## 7. Initialise model, optimiser, and scheduler

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = df["label_id"].nunique()

model = BiGRUAttentionModel(
    input_size=INPUT_SIZE,
    hidden_size=256,
    num_classes=NUM_CLASSES,
    num_layers=2,
    dropout=0.4
).to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=3e-4,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="max",
    factor=0.5,
    patience=5
)

print("Using device:", device)
print("Number of classes:", NUM_CLASSES)
print(model)

Using device: cpu
Number of classes: 300
BiGRUAttentionModel(
  (input_projection): Sequential(
    (0): Linear(in_features=516, out_features=256, bias=True)
    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.4, inplace=False)
  )
  (gru): GRU(256, 256, num_layers=2, batch_first=True, dropout=0.4, bidirectional=True)
  (attention): Sequential(
    (0): Linear(in_features=512, out_features=256, bias=True)
    (1): Tanh()
    (2): Linear(in_features=256, out_features=1, bias=True)
  )
  (classifier): Sequential(
    (0): Linear(in_features=512, out_features=256, bias=True)
    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=256, out_features=300, bias=True)
  )
)

## 8. Training and evaluation helper functions

In [10]:
def top_k_accuracy(outputs, labels, k=5):
    _, top_k_preds = outputs.topk(k, dim=1)
    correct = top_k_preds.eq(labels.view(-1, 1).expand_as(top_k_preds))
    return correct.any(dim=1).float().mean().item()

def run_epoch(model, loader, optimizer=None, phase="Train", epoch=1, total_epochs=1):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    total_loss = 0
    total_top1 = 0
    total_top3 = 0
    total_top5 = 0
    all_preds = []
    all_labels = []

    progress_bar = tqdm(loader, desc=f"Epoch {epoch}/{total_epochs} [{phase}]", leave=False)

    with torch.set_grad_enabled(is_train):
        for step, (x, y) in enumerate(progress_bar, start=1):
            x = x.to(device)
            y = y.to(device)

            if is_train:
                optimizer.zero_grad()

            outputs = model(x)
            loss = criterion(outputs, y)

            if is_train:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            preds = torch.argmax(outputs, dim=1)

            batch_top1 = (preds == y).float().mean().item()
            batch_top3 = top_k_accuracy(outputs, y, k=3)
            batch_top5 = top_k_accuracy(outputs, y, k=5)

            total_loss += loss.item()
            total_top1 += batch_top1
            total_top3 += batch_top3
            total_top5 += batch_top5

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y.cpu().numpy())

            progress_bar.set_postfix({
                "step": f"{step}/{len(loader)}",
                "loss": f"{loss.item():.4f}",
                "top1": f"{batch_top1:.4f}",
                "top5": f"{batch_top5:.4f}"
            })

    avg_loss = total_loss / len(loader)
    avg_top1 = total_top1 / len(loader)
    avg_top3 = total_top3 / len(loader)
    avg_top5 = total_top5 / len(loader)
    macro_f1 = f1_score(all_labels, all_preds, average="macro", zero_division=0)

    return avg_loss, avg_top1, avg_top3, avg_top5, macro_f1

## 9. Train WLASL300 model

In [11]:
history = {
    "train_loss": [],
    "train_top1": [],
    "train_top3": [],
    "train_top5": [],
    "train_f1": [],
    "val_loss": [],
    "val_top1": [],
    "val_top3": [],
    "val_top5": [],
    "val_f1": [],
    "lr": []
}

best_val_f1 = 0.0
best_val_top5 = 0.0
epochs_without_improvement = 0

print("=" * 80)
print("Be My Ear - WLASL300 BiGRU + Temporal Attention Training")
print("=" * 80)
print(f"Device: {device}")
print(f"Input shape: (60, {INPUT_SIZE})")
print(f"Classes: {NUM_CLASSES}")
print(f"Train samples: {len(train_df)}")
print(f"Validation samples: {len(val_df)}")
print(f"Test samples: {len(test_df)}")
print(f"Epochs: {EPOCHS}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Model save path: {MODEL_PATH}")
print("=" * 80)

start_time = time.time()

for epoch in range(1, EPOCHS + 1):
    print(f"\nEpoch {epoch}/{EPOCHS}")
    print("-" * 80)

    train_loss, train_top1, train_top3, train_top5, train_f1 = run_epoch(
        model, train_loader, optimizer=optimizer, phase="Training", epoch=epoch, total_epochs=EPOCHS
    )

    val_loss, val_top1, val_top3, val_top5, val_f1 = run_epoch(
        model, val_loader, optimizer=None, phase="Validation", epoch=epoch, total_epochs=EPOCHS
    )

    scheduler.step(val_f1)
    current_lr = optimizer.param_groups[0]["lr"]

    history["train_loss"].append(train_loss)
    history["train_top1"].append(train_top1)
    history["train_top3"].append(train_top3)
    history["train_top5"].append(train_top5)
    history["train_f1"].append(train_f1)
    history["val_loss"].append(val_loss)
    history["val_top1"].append(val_top1)
    history["val_top3"].append(val_top3)
    history["val_top5"].append(val_top5)
    history["val_f1"].append(val_f1)
    history["lr"].append(current_lr)

    improved = val_f1 > best_val_f1

    if improved:
        best_val_f1 = val_f1
        best_val_top5 = val_top5
        epochs_without_improvement = 0

        torch.save({
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "best_val_f1": best_val_f1,
            "best_val_top5": best_val_top5,
            "num_classes": NUM_CLASSES,
            "input_size": INPUT_SIZE,
            "sequence_length": SEQUENCE_LENGTH,
            "use_velocity": USE_VELOCITY,
            "architecture": "BiGRUAttentionModel"
        }, MODEL_PATH)

        save_status = "Saved new best model"
    else:
        epochs_without_improvement += 1
        save_status = "No improvement"

    print(f"Train | Loss: {train_loss:.4f} | Top-1: {train_top1:.4f} | Top-3: {train_top3:.4f} | Top-5: {train_top5:.4f} | F1: {train_f1:.4f}")
    print(f"Val   | Loss: {val_loss:.4f} | Top-1: {val_top1:.4f} | Top-3: {val_top3:.4f} | Top-5: {val_top5:.4f} | F1: {val_f1:.4f}")
    print(f"Learning rate: {current_lr:.8f}")
    print(f"Status: {save_status}")
    print(f"Best Val F1 so far: {best_val_f1:.4f}")
    print(f"Best Val Top-5 so far: {best_val_top5:.4f}")
    print(f"Epochs without improvement: {epochs_without_improvement}/{EARLY_STOPPING_PATIENCE}")

    if epochs_without_improvement >= EARLY_STOPPING_PATIENCE:
        print("\nEarly stopping triggered.")
        break

training_minutes = (time.time() - start_time) / 60

print("\n" + "=" * 80)
print("Training completed")
print("=" * 80)
print(f"Total training time: {training_minutes:.2f} minutes")
print(f"Best validation F1: {best_val_f1:.4f}")
print(f"Best validation Top-5: {best_val_top5:.4f}")
print(f"Best model saved to: {MODEL_PATH}")
print("=" * 80)

================================================================================
Be My Ear - WLASL300 BiGRU + Temporal Attention Training
================================================================================
Device: cpu
Input shape: (60, 516)
Classes: 300
Train samples: 1870
Validation samples: 395
Test samples: 395
Epochs: 60
Batch size: 32
Model save path: E:\Be_My_Ear\models\ASL\WLASL300\bigru_attention_wlasl300.pt
================================================================================

Epoch 1/60
--------------------------------------------------------------------------------

Train | Loss: 5.7250 | Top-1: 0.0069 | Top-3: 0.0212 | Top-5: 0.0334 | F1: 0.0036
Val   | Loss: 5.5694 | Top-1: 0.0072 | Top-3: 0.0168 | Top-5: 0.0334 | F1: 0.0016
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0016
Best Val Top-5 so far: 0.0334
Epochs without improvement: 0/15

Epoch 2/60
--------------------------------------------------------------------------------

Train | Loss: 5.3841 | Top-1: 0.0164 | Top-3: 0.0572 | Top-5: 0.0853 | F1: 0.0078
Val   | Loss: 5.3252 | Top-1: 0.0240 | Top-3: 0.0505 | Top-5: 0.0769 | F1: 0.0078
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0078
Best Val Top-5 so far: 0.0769
Epochs without improvement: 0/15

Epoch 3/60
--------------------------------------------------------------------------------

Train | Loss: 5.0807 | Top-1: 0.0461 | Top-3: 0.1118 | Top-5: 0.1601 | F1: 0.0241
Val   | Loss: 5.0790 | Top-1: 0.0553 | Top-3: 0.1080 | Top-5: 0.1296 | F1: 0.0217
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0217
Best Val Top-5 so far: 0.1296
Epochs without improvement: 0/15

Epoch 4/60
--------------------------------------------------------------------------------

Train | Loss: 4.8168 | Top-1: 0.0817 | Top-3: 0.1636 | Top-5: 0.2247 | F1: 0.0520
Val   | Loss: 4.9265 | Top-1: 0.0553 | Top-3: 0.1368 | Top-5: 0.1799 | F1: 0.0276
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0276
Best Val Top-5 so far: 0.1799
Epochs without improvement: 0/15

Epoch 5/60
--------------------------------------------------------------------------------

Train | Loss: 4.5345 | Top-1: 0.1224 | Top-3: 0.2468 | Top-5: 0.3305 | F1: 0.0802
Val   | Loss: 4.7285 | Top-1: 0.0671 | Top-3: 0.1604 | Top-5: 0.2179 | F1: 0.0339
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0339
Best Val Top-5 so far: 0.2179
Epochs without improvement: 0/15

Epoch 6/60
--------------------------------------------------------------------------------

Train | Loss: 4.3230 | Top-1: 0.1486 | Top-3: 0.3002 | Top-5: 0.3860 | F1: 0.0966
Val   | Loss: 4.5937 | Top-1: 0.0887 | Top-3: 0.1702 | Top-5: 0.2515 | F1: 0.0532
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0532
Best Val Top-5 so far: 0.2515
Epochs without improvement: 0/15

Epoch 7/60
--------------------------------------------------------------------------------

Train | Loss: 4.1148 | Top-1: 0.2079 | Top-3: 0.3734 | Top-5: 0.4592 | F1: 0.1514
Val   | Loss: 4.5010 | Top-1: 0.0935 | Top-3: 0.1702 | Top-5: 0.2375 | F1: 0.0597
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0597
Best Val Top-5 so far: 0.2375
Epochs without improvement: 0/15

Epoch 8/60
--------------------------------------------------------------------------------

Train | Loss: 3.9450 | Top-1: 0.2266 | Top-3: 0.4061 | Top-5: 0.5011 | F1: 0.1667
Val   | Loss: 4.3539 | Top-1: 0.1031 | Top-3: 0.2605 | Top-5: 0.3492 | F1: 0.0688
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0688
Best Val Top-5 so far: 0.3492
Epochs without improvement: 0/15

Epoch 9/60
--------------------------------------------------------------------------------

Train | Loss: 3.7806 | Top-1: 0.2722 | Top-3: 0.4525 | Top-5: 0.5635 | F1: 0.2105
Val   | Loss: 4.2257 | Top-1: 0.1125 | Top-3: 0.2970 | Top-5: 0.3833 | F1: 0.0754
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.0754
Best Val Top-5 so far: 0.3833
Epochs without improvement: 0/15

Epoch 10/60
--------------------------------------------------------------------------------

Train | Loss: 3.6234 | Top-1: 0.3265 | Top-3: 0.5127 | Top-5: 0.6152 | F1: 0.2685
Val   | Loss: 4.1491 | Top-1: 0.1628 | Top-3: 0.3114 | Top-5: 0.4067 | F1: 0.1034
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1034
Best Val Top-5 so far: 0.4067
Epochs without improvement: 0/15

Epoch 11/60
--------------------------------------------------------------------------------

Train | Loss: 3.4858 | Top-1: 0.3291 | Top-3: 0.5450 | Top-5: 0.6405 | F1: 0.2662
Val   | Loss: 4.0904 | Top-1: 0.1510 | Top-3: 0.3424 | Top-5: 0.4167 | F1: 0.1056
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1056
Best Val Top-5 so far: 0.4167
Epochs without improvement: 0/15

Epoch 12/60
--------------------------------------------------------------------------------

Train | Loss: 3.2620 | Top-1: 0.3946 | Top-3: 0.6126 | Top-5: 0.7127 | F1: 0.3177
Val   | Loss: 3.9700 | Top-1: 0.1892 | Top-3: 0.3619 | Top-5: 0.4432 | F1: 0.1342
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1342
Best Val Top-5 so far: 0.4432
Epochs without improvement: 0/15

Epoch 13/60
--------------------------------------------------------------------------------

Train | Loss: 3.1283 | Top-1: 0.4339 | Top-3: 0.6541 | Top-5: 0.7441 | F1: 0.3614
Val   | Loss: 3.9338 | Top-1: 0.1726 | Top-3: 0.3691 | Top-5: 0.4744 | F1: 0.1184
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.1342
Best Val Top-5 so far: 0.4432
Epochs without improvement: 1/15

Epoch 14/60
--------------------------------------------------------------------------------

Train | Loss: 2.9805 | Top-1: 0.4666 | Top-3: 0.6899 | Top-5: 0.7748 | F1: 0.3895
Val   | Loss: 3.8374 | Top-1: 0.2177 | Top-3: 0.4023 | Top-5: 0.4956 | F1: 0.1468
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1468
Best Val Top-5 so far: 0.4956
Epochs without improvement: 0/15

Epoch 15/60
--------------------------------------------------------------------------------

Train | Loss: 2.9012 | Top-1: 0.4772 | Top-3: 0.7010 | Top-5: 0.7887 | F1: 0.4080
Val   | Loss: 3.7552 | Top-1: 0.2229 | Top-3: 0.4264 | Top-5: 0.5363 | F1: 0.1677
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1677
Best Val Top-5 so far: 0.5363
Epochs without improvement: 0/15

Epoch 16/60
--------------------------------------------------------------------------------

Train | Loss: 2.7716 | Top-1: 0.5282 | Top-3: 0.7346 | Top-5: 0.8238 | F1: 0.4735
Val   | Loss: 3.6936 | Top-1: 0.2229 | Top-3: 0.4288 | Top-5: 0.5437 | F1: 0.1787
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.1787
Best Val Top-5 so far: 0.5437
Epochs without improvement: 0/15

Epoch 17/60
--------------------------------------------------------------------------------

Train | Loss: 2.6130 | Top-1: 0.5621 | Top-3: 0.7664 | Top-5: 0.8448 | F1: 0.4974
Val   | Loss: 3.6621 | Top-1: 0.2522 | Top-3: 0.4412 | Top-5: 0.5465 | F1: 0.2035
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2035
Best Val Top-5 so far: 0.5465
Epochs without improvement: 0/15

Epoch 18/60
--------------------------------------------------------------------------------

Train | Loss: 2.4940 | Top-1: 0.5956 | Top-3: 0.8001 | Top-5: 0.8638 | F1: 0.5370
Val   | Loss: 3.5735 | Top-1: 0.2327 | Top-3: 0.4600 | Top-5: 0.5463 | F1: 0.1809
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2035
Best Val Top-5 so far: 0.5465
Epochs without improvement: 1/15

Epoch 19/60
--------------------------------------------------------------------------------

Train | Loss: 2.3484 | Top-1: 0.6219 | Top-3: 0.8309 | Top-5: 0.8913 | F1: 0.5596
Val   | Loss: 3.5107 | Top-1: 0.2496 | Top-3: 0.4797 | Top-5: 0.5559 | F1: 0.2051
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2051
Best Val Top-5 so far: 0.5559
Epochs without improvement: 0/15

Epoch 20/60
--------------------------------------------------------------------------------

Train | Loss: 2.1786 | Top-1: 0.6671 | Top-3: 0.8583 | Top-5: 0.9167 | F1: 0.6128
Val   | Loss: 3.4515 | Top-1: 0.2662 | Top-3: 0.4744 | Top-5: 0.5944 | F1: 0.2169
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2169
Best Val Top-5 so far: 0.5944
Epochs without improvement: 0/15

Epoch 21/60
--------------------------------------------------------------------------------

Train | Loss: 2.1182 | Top-1: 0.6802 | Top-3: 0.8616 | Top-5: 0.9225 | F1: 0.6374
Val   | Loss: 3.3968 | Top-1: 0.2660 | Top-3: 0.4792 | Top-5: 0.5992 | F1: 0.2174
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2174
Best Val Top-5 so far: 0.5992
Epochs without improvement: 0/15

Epoch 22/60
--------------------------------------------------------------------------------

Train | Loss: 1.9692 | Top-1: 0.7132 | Top-3: 0.8842 | Top-5: 0.9299 | F1: 0.6785
Val   | Loss: 3.3652 | Top-1: 0.2878 | Top-3: 0.5055 | Top-5: 0.6112 | F1: 0.2355
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2355
Best Val Top-5 so far: 0.6112
Epochs without improvement: 0/15

Epoch 23/60
--------------------------------------------------------------------------------

Train | Loss: 1.9061 | Top-1: 0.7481 | Top-3: 0.9001 | Top-5: 0.9421 | F1: 0.7225
Val   | Loss: 3.3111 | Top-1: 0.3000 | Top-3: 0.5223 | Top-5: 0.6230 | F1: 0.2593
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2593
Best Val Top-5 so far: 0.6230
Epochs without improvement: 0/15

Epoch 24/60
--------------------------------------------------------------------------------

Train | Loss: 1.8366 | Top-1: 0.7485 | Top-3: 0.9075 | Top-5: 0.9464 | F1: 0.7255
Val   | Loss: 3.2525 | Top-1: 0.2902 | Top-3: 0.5369 | Top-5: 0.6591 | F1: 0.2398
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2593
Best Val Top-5 so far: 0.6230
Epochs without improvement: 1/15

Epoch 25/60
--------------------------------------------------------------------------------

Train | Loss: 1.6813 | Top-1: 0.7965 | Top-3: 0.9310 | Top-5: 0.9543 | F1: 0.7610
Val   | Loss: 3.2304 | Top-1: 0.2924 | Top-3: 0.5417 | Top-5: 0.6425 | F1: 0.2313
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2593
Best Val Top-5 so far: 0.6230
Epochs without improvement: 2/15

Epoch 26/60
--------------------------------------------------------------------------------

Train | Loss: 1.6230 | Top-1: 0.8148 | Top-3: 0.9342 | Top-5: 0.9628 | F1: 0.7892
Val   | Loss: 3.1616 | Top-1: 0.3330 | Top-3: 0.5487 | Top-5: 0.6495 | F1: 0.2713
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2713
Best Val Top-5 so far: 0.6495
Epochs without improvement: 0/15

Epoch 27/60
--------------------------------------------------------------------------------

Train | Loss: 1.5353 | Top-1: 0.8281 | Top-3: 0.9458 | Top-5: 0.9707 | F1: 0.8019
Val   | Loss: 3.1256 | Top-1: 0.3142 | Top-3: 0.5658 | Top-5: 0.6689 | F1: 0.2689
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2713
Best Val Top-5 so far: 0.6495
Epochs without improvement: 1/15

Epoch 28/60
--------------------------------------------------------------------------------

Train | Loss: 1.4802 | Top-1: 0.8435 | Top-3: 0.9541 | Top-5: 0.9750 | F1: 0.8213
Val   | Loss: 3.0692 | Top-1: 0.3429 | Top-3: 0.5778 | Top-5: 0.6759 | F1: 0.2855
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.2855
Best Val Top-5 so far: 0.6759
Epochs without improvement: 0/15

Epoch 29/60
--------------------------------------------------------------------------------

Train | Loss: 1.3559 | Top-1: 0.8724 | Top-3: 0.9688 | Top-5: 0.9793 | F1: 0.8529
Val   | Loss: 3.0817 | Top-1: 0.3381 | Top-3: 0.5487 | Top-5: 0.6569 | F1: 0.2724
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2855
Best Val Top-5 so far: 0.6759
Epochs without improvement: 1/15

Epoch 30/60
--------------------------------------------------------------------------------

Train | Loss: 1.3203 | Top-1: 0.8773 | Top-3: 0.9649 | Top-5: 0.9797 | F1: 0.8627
Val   | Loss: 3.0627 | Top-1: 0.3403 | Top-3: 0.5730 | Top-5: 0.6663 | F1: 0.2798
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.2855
Best Val Top-5 so far: 0.6759
Epochs without improvement: 2/15

Epoch 31/60
--------------------------------------------------------------------------------

Train | Loss: 1.2324 | Top-1: 0.8966 | Top-3: 0.9756 | Top-5: 0.9883 | F1: 0.8809
Val   | Loss: 3.0595 | Top-1: 0.3645 | Top-3: 0.5610 | Top-5: 0.6543 | F1: 0.3063
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.3063
Best Val Top-5 so far: 0.6543
Epochs without improvement: 0/15

Epoch 32/60
--------------------------------------------------------------------------------

Train | Loss: 1.1472 | Top-1: 0.9216 | Top-3: 0.9841 | Top-5: 0.9952 | F1: 0.9131
Val   | Loss: 3.0526 | Top-1: 0.3311 | Top-3: 0.5824 | Top-5: 0.6687 | F1: 0.2827
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3063
Best Val Top-5 so far: 0.6543
Epochs without improvement: 1/15

Epoch 33/60
--------------------------------------------------------------------------------

Train | Loss: 1.1183 | Top-1: 0.9234 | Top-3: 0.9824 | Top-5: 0.9942 | F1: 0.9161
Val   | Loss: 3.0357 | Top-1: 0.3573 | Top-3: 0.5704 | Top-5: 0.6761 | F1: 0.3042
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3063
Best Val Top-5 so far: 0.6543
Epochs without improvement: 2/15

Epoch 34/60
--------------------------------------------------------------------------------

Train | Loss: 1.0463 | Top-1: 0.9370 | Top-3: 0.9894 | Top-5: 0.9968 | F1: 0.9241
Val   | Loss: 2.9658 | Top-1: 0.3597 | Top-3: 0.5874 | Top-5: 0.6906 | F1: 0.3081
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.3081
Best Val Top-5 so far: 0.6906
Epochs without improvement: 0/15

Epoch 35/60
--------------------------------------------------------------------------------

Train | Loss: 1.0276 | Top-1: 0.9363 | Top-3: 0.9868 | Top-5: 0.9942 | F1: 0.9287
Val   | Loss: 3.0400 | Top-1: 0.3407 | Top-3: 0.5732 | Top-5: 0.6571 | F1: 0.2910
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3081
Best Val Top-5 so far: 0.6906
Epochs without improvement: 1/15

Epoch 36/60
--------------------------------------------------------------------------------

Train | Loss: 0.9843 | Top-1: 0.9544 | Top-3: 0.9931 | Top-5: 0.9974 | F1: 0.9460
Val   | Loss: 3.0058 | Top-1: 0.3453 | Top-3: 0.5852 | Top-5: 0.6761 | F1: 0.2856
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3081
Best Val Top-5 so far: 0.6906
Epochs without improvement: 2/15

Epoch 37/60
--------------------------------------------------------------------------------

Train | Loss: 0.9759 | Top-1: 0.9454 | Top-3: 0.9905 | Top-5: 0.9968 | F1: 0.9371
Val   | Loss: 3.0346 | Top-1: 0.3407 | Top-3: 0.5802 | Top-5: 0.6903 | F1: 0.2894
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3081
Best Val Top-5 so far: 0.6906
Epochs without improvement: 3/15

Epoch 38/60
--------------------------------------------------------------------------------

Train | Loss: 0.9196 | Top-1: 0.9597 | Top-3: 0.9947 | Top-5: 0.9979 | F1: 0.9565
Val   | Loss: 3.0264 | Top-1: 0.3859 | Top-3: 0.5802 | Top-5: 0.6764 | F1: 0.3275
Learning rate: 0.00030000
Status: Saved new best model
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 0/15

Epoch 39/60
--------------------------------------------------------------------------------

Train | Loss: 0.9084 | Top-1: 0.9616 | Top-3: 0.9952 | Top-5: 0.9989 | F1: 0.9576
Val   | Loss: 3.0287 | Top-1: 0.3623 | Top-3: 0.6016 | Top-5: 0.6831 | F1: 0.2954
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 1/15

Epoch 40/60
--------------------------------------------------------------------------------

Train | Loss: 0.8788 | Top-1: 0.9612 | Top-3: 0.9968 | Top-5: 0.9984 | F1: 0.9573
Val   | Loss: 3.0441 | Top-1: 0.3575 | Top-3: 0.5968 | Top-5: 0.6903 | F1: 0.2976
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 2/15

Epoch 41/60
--------------------------------------------------------------------------------

Train | Loss: 0.8580 | Top-1: 0.9688 | Top-3: 0.9968 | Top-5: 0.9995 | F1: 0.9627
Val   | Loss: 3.0445 | Top-1: 0.3621 | Top-3: 0.5778 | Top-5: 0.6547 | F1: 0.2920
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 3/15

Epoch 42/60
--------------------------------------------------------------------------------

Train | Loss: 0.8421 | Top-1: 0.9712 | Top-3: 0.9963 | Top-5: 0.9989 | F1: 0.9704
Val   | Loss: 3.0581 | Top-1: 0.3621 | Top-3: 0.6112 | Top-5: 0.6761 | F1: 0.2997
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 4/15

Epoch 43/60
--------------------------------------------------------------------------------

Train | Loss: 0.8095 | Top-1: 0.9772 | Top-3: 0.9968 | Top-5: 1.0000 | F1: 0.9721
Val   | Loss: 3.0074 | Top-1: 0.3359 | Top-3: 0.6016 | Top-5: 0.7050 | F1: 0.2837
Learning rate: 0.00030000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 5/15

Epoch 44/60
--------------------------------------------------------------------------------

Train | Loss: 0.7987 | Top-1: 0.9739 | Top-3: 0.9968 | Top-5: 1.0000 | F1: 0.9677
Val   | Loss: 3.0547 | Top-1: 0.3503 | Top-3: 0.5802 | Top-5: 0.6764 | F1: 0.2860
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 6/15

Epoch 45/60
--------------------------------------------------------------------------------

Train | Loss: 0.7746 | Top-1: 0.9815 | Top-3: 0.9989 | Top-5: 1.0000 | F1: 0.9771
Val   | Loss: 3.0373 | Top-1: 0.3837 | Top-3: 0.6018 | Top-5: 0.6475 | F1: 0.3202
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 7/15

Epoch 46/60
--------------------------------------------------------------------------------

Train | Loss: 0.7342 | Top-1: 0.9905 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9902
Val   | Loss: 2.9797 | Top-1: 0.3645 | Top-3: 0.6233 | Top-5: 0.7098 | F1: 0.3043
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 8/15

Epoch 47/60
--------------------------------------------------------------------------------

Train | Loss: 0.7228 | Top-1: 0.9873 | Top-3: 0.9995 | Top-5: 1.0000 | F1: 0.9856
Val   | Loss: 2.9568 | Top-1: 0.3813 | Top-3: 0.6357 | Top-5: 0.7148 | F1: 0.3169
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 9/15

Epoch 48/60
--------------------------------------------------------------------------------

Train | Loss: 0.7161 | Top-1: 0.9915 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9921
Val   | Loss: 2.9773 | Top-1: 0.3934 | Top-3: 0.6375 | Top-5: 0.7384 | F1: 0.3237
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3275
Best Val Top-5 so far: 0.6764
Epochs without improvement: 10/15

Epoch 49/60
--------------------------------------------------------------------------------

Train | Loss: 0.7059 | Top-1: 0.9899 | Top-3: 0.9995 | Top-5: 0.9995 | F1: 0.9879
Val   | Loss: 2.9150 | Top-1: 0.4028 | Top-3: 0.6136 | Top-5: 0.7192 | F1: 0.3339
Learning rate: 0.00015000
Status: Saved new best model
Best Val F1 so far: 0.3339
Best Val Top-5 so far: 0.7192
Epochs without improvement: 0/15

Epoch 50/60
--------------------------------------------------------------------------------

Train | Loss: 0.7043 | Top-1: 0.9905 | Top-3: 0.9995 | Top-5: 0.9995 | F1: 0.9903
Val   | Loss: 2.9913 | Top-1: 0.3743 | Top-3: 0.6018 | Top-5: 0.7052 | F1: 0.3246
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3339
Best Val Top-5 so far: 0.7192
Epochs without improvement: 1/15

Epoch 51/60
--------------------------------------------------------------------------------

Train | Loss: 0.7049 | Top-1: 0.9899 | Top-3: 0.9995 | Top-5: 1.0000 | F1: 0.9889
Val   | Loss: 2.9706 | Top-1: 0.4054 | Top-3: 0.6261 | Top-5: 0.7122 | F1: 0.3527
Learning rate: 0.00015000
Status: Saved new best model
Best Val F1 so far: 0.3527
Best Val Top-5 so far: 0.7122
Epochs without improvement: 0/15

Epoch 52/60
--------------------------------------------------------------------------------

Train | Loss: 0.7007 | Top-1: 0.9887 | Top-3: 0.9995 | Top-5: 1.0000 | F1: 0.9890
Val   | Loss: 2.9540 | Top-1: 0.3958 | Top-3: 0.6257 | Top-5: 0.7050 | F1: 0.3268
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3527
Best Val Top-5 so far: 0.7122
Epochs without improvement: 1/15

Epoch 53/60
--------------------------------------------------------------------------------

Train | Loss: 0.6891 | Top-1: 0.9951 | Top-3: 0.9995 | Top-5: 1.0000 | F1: 0.9952
Val   | Loss: 2.9858 | Top-1: 0.3936 | Top-3: 0.6353 | Top-5: 0.7194 | F1: 0.3402
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3527
Best Val Top-5 so far: 0.7122
Epochs without improvement: 2/15

Epoch 54/60
--------------------------------------------------------------------------------

Train | Loss: 0.6903 | Top-1: 0.9921 | Top-3: 0.9995 | Top-5: 1.0000 | F1: 0.9932
Val   | Loss: 2.9423 | Top-1: 0.3907 | Top-3: 0.6473 | Top-5: 0.7146 | F1: 0.3304
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3527
Best Val Top-5 so far: 0.7122
Epochs without improvement: 3/15

Epoch 55/60
--------------------------------------------------------------------------------

Train | Loss: 0.6745 | Top-1: 0.9936 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9935
Val   | Loss: 2.9090 | Top-1: 0.4100 | Top-3: 0.6449 | Top-5: 0.7146 | F1: 0.3417
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3527
Best Val Top-5 so far: 0.7122
Epochs without improvement: 4/15

Epoch 56/60
--------------------------------------------------------------------------------

Train | Loss: 0.6823 | Top-1: 0.9931 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9940
Val   | Loss: 2.9330 | Top-1: 0.4124 | Top-3: 0.6351 | Top-5: 0.7240 | F1: 0.3555
Learning rate: 0.00015000
Status: Saved new best model
Best Val F1 so far: 0.3555
Best Val Top-5 so far: 0.7240
Epochs without improvement: 0/15

Epoch 57/60
--------------------------------------------------------------------------------

Train | Loss: 0.6773 | Top-1: 0.9930 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9932
Val   | Loss: 2.9679 | Top-1: 0.3910 | Top-3: 0.6401 | Top-5: 0.7168 | F1: 0.3418
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3555
Best Val Top-5 so far: 0.7240
Epochs without improvement: 1/15

Epoch 58/60
--------------------------------------------------------------------------------

Train | Loss: 0.6712 | Top-1: 0.9952 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9947
Val   | Loss: 2.9056 | Top-1: 0.4102 | Top-3: 0.6543 | Top-5: 0.7336 | F1: 0.3530
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3555
Best Val Top-5 so far: 0.7240
Epochs without improvement: 2/15

Epoch 59/60
--------------------------------------------------------------------------------

Train | Loss: 0.6727 | Top-1: 0.9931 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9921
Val   | Loss: 2.9173 | Top-1: 0.4006 | Top-3: 0.6427 | Top-5: 0.7028 | F1: 0.3441
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3555
Best Val Top-5 so far: 0.7240
Epochs without improvement: 3/15

Epoch 60/60
--------------------------------------------------------------------------------

Train | Loss: 0.6613 | Top-1: 0.9952 | Top-3: 1.0000 | Top-5: 1.0000 | F1: 0.9935
Val   | Loss: 2.9548 | Top-1: 0.4054 | Top-3: 0.6257 | Top-5: 0.7192 | F1: 0.3440
Learning rate: 0.00015000
Status: No improvement
Best Val F1 so far: 0.3555
Best Val Top-5 so far: 0.7240
Epochs without improvement: 4/15

================================================================================
Training completed
================================================================================
Total training time: 39.02 minutes
Best validation F1: 0.3555
Best validation Top-5: 0.7240
Best model saved to: E:\Be_My_Ear\models\ASL\WLASL300\bigru_attention_wlasl300.pt
================================================================================

## 10. Save training history and evaluate test set

In [12]:
history_df = pd.DataFrame(history)
history_df.to_csv(HISTORY_PATH, index=False)

print("Saved history to:", HISTORY_PATH)
history_df.head()

Saved history to: E:\Be_My_Ear\models\ASL\WLASL300\bigru_attention_wlasl300_history.csv

,train_loss,train_top1,train_top3,train_top5,train_f1,val_loss,val_top1,val_top3,val_top5,val_f1,lr
0,5.724970,0.006886,0.021186,0.033369,0.003606,5.569398,0.007212,0.016827,0.033435,0.001638,0.0003
1,5.384116,0.016419,0.057203,0.085275,0.007828,5.325166,0.024038,0.050481,0.076923,0.007799,0.0003
2,5.080695,0.046081,0.111758,0.160109,0.024064,5.079000,0.055288,0.107955,0.129589,0.021702,0.0003
3,4.816849,0.081719,0.163590,0.224652,0.051995,4.926520,0.055288,0.136801,0.179851,0.027575,0.0003
4,4.534488,0.122427,0.246822,0.330508,0.080196,4.728474,0.067089,0.160402,0.217876,0.033916,0.0003

In [13]:
checkpoint = torch.load(MODEL_PATH, map_location=device)
model.load_state_dict(checkpoint["model_state_dict"])

test_loss, test_top1, test_top3, test_top5, test_f1 = run_epoch(
    model, test_loader, optimizer=None, phase="Test", epoch=1, total_epochs=1
)

print("=" * 80)
print("WLASL300 Test Evaluation")
print("=" * 80)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Top-1 Accuracy: {test_top1:.4f}")
print(f"Test Top-3 Accuracy: {test_top3:.4f}")
print(f"Test Top-5 Accuracy: {test_top5:.4f}")
print(f"Test Macro F1: {test_f1:.4f}")
print("=" * 80)

================================================================================
WLASL300 Test Evaluation
================================================================================
Test Loss: 3.1388
Test Top-1 Accuracy: 0.3595
Test Top-3 Accuracy: 0.5828
Test Top-5 Accuracy: 0.6737
Test Macro F1: 0.2969
================================================================================

In [14]:
RESULT_FILE = MODEL_DIR / f"bigru_attention_{PREFIX}_result_summary.csv"

result_df = pd.DataFrame([{
    "dataset": DATASET_NAME,
    "model": "BiGRU + Temporal Attention",
    "clean_samples": len(df),
    "classes": NUM_CLASSES,
    "input_shape": f"(60, {INPUT_SIZE})",
    "velocity_features": USE_VELOCITY,
    "best_val_f1": checkpoint["best_val_f1"],
    "best_val_top5": checkpoint["best_val_top5"],
    "checkpoint_epoch": checkpoint["epoch"],
    "test_top1_accuracy": test_top1,
    "test_top3_accuracy": test_top3,
    "test_top5_accuracy": test_top5,
    "test_macro_f1": test_f1,
    "model_path": str(MODEL_PATH),
    "history_path": str(HISTORY_PATH)
}])

result_df.to_csv(RESULT_FILE, index=False)

print("Saved result summary to:", RESULT_FILE)
result_df

Saved result summary to: E:\Be_My_Ear\models\ASL\WLASL300\bigru_attention_wlasl300_result_summary.csv

,dataset,model,clean_samples,classes,input_shape,velocity_features,best_val_f1,best_val_top5,checkpoint_epoch,test_top1_accuracy,test_top3_accuracy,test_top5_accuracy,test_macro_f1,model_path,history_path
0,WLASL300,BiGRU + Temporal Attention,2660,300,"(60, 516)",True,0.35554,0.723995,56,0.359484,0.582823,0.673733,0.296921,E:\Be_My_Ear\models\ASL\WLASL300\bigru_attenti...,E:\Be_My_Ear\models\ASL\WLASL300\bigru_attenti...

## Final summary

After this notebook, continue with:

```text
05_evaluate_wlasl300_bigru_attention.ipynb
```